name: deploy

on:
  push:
    branches: 
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v1
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Install Dependency
      run: npm ci
   
    - name: Build
      uses: npm run build
    
    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
